**Q1 Represent the data in Numpy array to perform following actions**

***Downloaded the excel file in csv format and then imported csv and numpy , created an empty list and added the data of csv to that list***

In [1]:
import csv

In [2]:
import numpy as np

In [3]:
data=[]

In [4]:
with open(r"C:\Users\cool_adarsh\Downloads\SampleTemperature Sheet - mysheet-csv.csv",'r') as csvfile2:
    file_reader=csv.reader(csvfile2,delimiter=',')
    for row in file_reader:
        data.append(row)
data=np.array(data)

In [5]:
data

array([['Temprature Sheet', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
       ['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['', 'Week 1', '6', '32', '8', '29', '14', '31', '13', '27', '12',
        '29', '14', '23', '6', '27'],
       ['', 'Week 2', '13', '21', '14', '26', '15', '32', '-13', '29',
        '14', '29', '13', '30', '11', '30'],
       ['', 'Week 3', '10', '22', '7', '20', '13', '21', '10', '30',
        '11', '21', '10', '28', '7', '21'],
       ['', 'Week 4', '7', '20', '8', '31', '8', '32', '8', '24', '8',
        '32', '6', '21', '8', '30'],
       ['December', 'Week 1', '1

In [6]:
data=np.delete(data,0,axis=0)

In [7]:
data=np.delete(data,0,axis=0)

In [8]:
d1=data[2:,:]
d1

array([['', 'Week 1', '6', '32', '8', '29', '14', '31', '13', '27', '12',
        '29', '14', '23', '6', '27'],
       ['', 'Week 2', '13', '21', '14', '26', '15', '32', '-13', '29',
        '14', '29', '13', '30', '11', '30'],
       ['', 'Week 3', '10', '22', '7', '20', '13', '21', '10', '30',
        '11', '21', '10', '28', '7', '21'],
       ['', 'Week 4', '7', '20', '8', '31', '8', '32', '8', '24', '8',
        '32', '6', '21', '8', '30'],
       ['December', 'Week 1', '14', '28', '14', '26', '15', '22', '6',
        '27', '9', '31', '11', '23', '14', '26'],
       ['', 'Week 2', '6', '32', '11', '32', '11', '21', '9', '28', '13',
        '23', '7', '28', '15', '21'],
       ['', 'Week 3', '11', '28', '15', '27', '13', '32', '8', '22',
        '11', '28', '11', '23', '11', '30'],
       ['', 'Week 4', '7', '27', '8', '25', '6', '21', '6', '32', '15',
        '20', '15', '22', '15', '23'],
       ['January', 'Week 1', '2', '22', '8', '21', '2', '19', '6', '21',
        '5', '19', '

In [9]:
#condition for the blank space in column 1
c1=d1[:,0]==''
c1

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True])

In [10]:
#filling of column 1 with months name
d1[:4,0:1] = 'November'
d1[5:8,0:1] = 'December'
d1[9:12,0:1] = 'January'
d1[13:16,0:1] = 'February'

In [11]:
d1

array([['November', 'Week 1', '6', '32', '8', '29', '14', '31', '13',
        '27', '12', '29', '14', '23', '6', '27'],
       ['November', 'Week 2', '13', '21', '14', '26', '15', '32', '-13',
        '29', '14', '29', '13', '30', '11', '30'],
       ['November', 'Week 3', '10', '22', '7', '20', '13', '21', '10',
        '30', '11', '21', '10', '28', '7', '21'],
       ['November', 'Week 4', '7', '20', '8', '31', '8', '32', '8', '24',
        '8', '32', '6', '21', '8', '30'],
       ['December', 'Week 1', '14', '28', '14', '26', '15', '22', '6',
        '27', '9', '31', '11', '23', '14', '26'],
       ['December', 'Week 2', '6', '32', '11', '32', '11', '21', '9',
        '28', '13', '23', '7', '28', '15', '21'],
       ['December', 'Week 3', '11', '28', '15', '27', '13', '32', '8',
        '22', '11', '28', '11', '23', '11', '30'],
       ['December', 'Week 4', '7', '27', '8', '25', '6', '21', '6', '32',
        '15', '20', '15', '22', '15', '23'],
       ['January', 'Week 1', '2', '22

In [12]:
# merging title
d2=np.vstack((data[0:2,:],d1))
d2

array([['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '6', '32', '8', '29', '14', '31', '13',
        '27', '12', '29', '14', '23', '6', '27'],
       ['November', 'Week 2', '13', '21', '14', '26', '15', '32', '-13',
        '29', '14', '29', '13', '30', '11', '30'],
       ['November', 'Week 3', '10', '22', '7', '20', '13', '21', '10',
        '30', '11', '21', '10', '28', '7', '21'],
       ['November', 'Week 4', '7', '20', '8', '31', '8', '32', '8', '24',
        '8', '32', '6', '21', '8', '30'],
       ['December', 'Week 1', '14', '28', '14', '26', '15', '22', '6',
        '27', '9', '31', '11', '23', '14', '26'],
       ['December', 'Week 2', '6', '32', '11', '3

In [13]:
#filling of blank space in row2
c2=data[0:1,:]==''
c2

array([[False, False, False,  True, False,  True, False,  True, False,
         True, False,  True, False,  True, False,  True]])

In [14]:
data[0:1,3:4]='Monday'
data[0:1,5:6]='Tuesday'
data[0:1,7:8]='Wednesday'
data[0:1,9:10]='Thursday'
data[0:1,11:12]='Friday'
data[0:1,13:14]='Saturday'
data[0:1,15:16]='Sunday'


In [15]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '6', '32', '8', '29', '14', '31', '13',
        '27', '12', '29', '14', '23', '6', '27'],
       ['November', 'Week 2', '13', '21', '14', '26', '15', '32', '-13',
        '29', '14', '29', '13', '30', '11', '30'],
       ['November', 'Week 3', '10', '22', '7', '20', '13', '21', '10',
        '30', '11', '21', '10', '28', '7', '21'],
       ['November', 'Week 4', '7', '20', '8', '31', '8', '32', '8', '24',
        '8', '32', '6', '21', '8', '30'],
       ['December', 'Week 1', '14', '28', '14', '26', '15', '22', '6',
        '27', '9', '31', '11', '23', '14'

**Q2 write the diamension and shape of the created array**

*to find the diamension we use the function array.ndim , and for shape we use array.shape*

In [16]:
data.ndim

2

In [17]:
data.shape

(18, 16)

**Q3 Print the daily temperature for the first week of each month**

In [18]:
data[0:4]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '6', '32', '8', '29', '14', '31', '13',
        '27', '12', '29', '14', '23', '6', '27'],
       ['November', 'Week 2', '13', '21', '14', '26', '15', '32', '-13',
        '29', '14', '29', '13', '30', '11', '30']], dtype='<U16')

In [19]:
cond_week1=data[:,1]=='week1'
cond_week1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [20]:
data_1 = data[cond_week1]
data_1 

array([], shape=(0, 16), dtype='<U16')

In [21]:
week1=np.vstack((data[0:2],data_1))
week1

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp']],
      dtype='<U16')

**Q4 Print the temperature for tuesday of each month**

In [22]:
temp=data[:,4:6]

In [23]:
temp

array([['Tuesday', 'Tuesday'],
       ['Min Temp', 'Max Temp'],
       ['8', '29'],
       ['14', '26'],
       ['7', '20'],
       ['8', '31'],
       ['14', '26'],
       ['11', '32'],
       ['15', '27'],
       ['8', '25'],
       ['8', '21'],
       ['8', '19'],
       ['7', '18'],
       ['8', '19'],
       ['11', '21'],
       ['9', '20'],
       ['8', '18'],
       ['12', '21']], dtype='<U16')

In [24]:
np.hstack((data[:,0:2],temp))

array([['Month', 'Week', 'Tuesday', 'Tuesday'],
       ['November', '', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '29'],
       ['November', 'Week 2', '14', '26'],
       ['November', 'Week 3', '7', '20'],
       ['November', 'Week 4', '8', '31'],
       ['December', 'Week 1', '14', '26'],
       ['December', 'Week 2', '11', '32'],
       ['December', 'Week 3', '15', '27'],
       ['December', 'Week 4', '8', '25'],
       ['January', 'Week 1', '8', '21'],
       ['January', 'Week 2', '8', '19'],
       ['January', 'Week 3', '7', '18'],
       ['January', 'Week 4', '8', '19'],
       ['February', 'Week 1', '11', '21'],
       ['February', 'Week 2', '9', '20'],
       ['February', 'Week 3', '8', '18'],
       ['February', 'Week 4', '12', '21']], dtype='<U16')

**Q5 print only the max temp. for all the week days of dec and feb**

In [25]:
max_temp=np.hstack((data[:,0:2],data[:,3::2]))
max_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['November', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['November', 'Week 1', '32', '29', '31', '27', '29', '23', '27'],
       ['November', 'Week 2', '21', '26', '32', '29', '29', '30', '30'],
       ['November', 'Week 3', '22', '20', '21', '30', '21', '28', '21'],
       ['November', 'Week 4', '20', '31', '32', '24', '32', '21', '30'],
       ['December', 'Week 1', '28', '26', '22', '27', '31', '23', '26'],
       ['December', 'Week 2', '32', '32', '21', '28', '23', '28', '21'],
       ['December', 'Week 3', '28', '27', '32', '22', '28', '23', '30'],
       ['December', 'Week 4', '27', '25', '21', '32', '20', '22', '23'],
       ['January', 'Week 1', '22', '21', '19', '21', '19', '7', '7'],
       ['January', 'Week 2', '18', '19', '21', '21', '22', '2', '6'],
       ['January', 'Week 3', '18', '18', '21', 

In [26]:
#december temperature
dec=max_temp[:,0]=='December'
dec_temp=max_temp[dec]

In [27]:
#february temperature
feb=max_temp[:,0]=='February'
feb_temp=max_temp[feb]

In [28]:
np.vstack(((max_temp[0:2,:],dec_temp,feb_temp)))

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['November', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['December', 'Week 1', '28', '26', '22', '27', '31', '23', '26'],
       ['December', 'Week 2', '32', '32', '21', '28', '23', '28', '21'],
       ['December', 'Week 3', '28', '27', '32', '22', '28', '23', '30'],
       ['December', 'Week 4', '27', '25', '21', '32', '20', '22', '23'],
       ['February', 'Week 1', '21', '21', '20', '22', '19', '71', '12'],
       ['February', 'Week 2', '22', '20', '20', '20', '19', '7', '7'],
       ['February', 'Week 3', '18', '18', '21', '22', '21', '9', '10'],
       ['February', 'Week 4', '22', '21', '19', '19', '20', '9', '12']],
      dtype='<U16')

**Q6 Print all the days along with the week number in the november when the minimum temperature was less than 8 degree.**

In [29]:
min_temp=np.hstack((data[:,0:2],data[:,2::2]))
min_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['November', '', 'Min Temp', 'Min Temp', 'Min Temp', 'Min Temp',
        'Min Temp', 'Min Temp', 'Min Temp'],
       ['November', 'Week 1', '6', '8', '14', '13', '12', '14', '6'],
       ['November', 'Week 2', '13', '14', '15', '-13', '14', '13', '11'],
       ['November', 'Week 3', '10', '7', '13', '10', '11', '10', '7'],
       ['November', 'Week 4', '7', '8', '8', '8', '8', '6', '8'],
       ['December', 'Week 1', '14', '14', '15', '6', '9', '11', '14'],
       ['December', 'Week 2', '6', '11', '11', '9', '13', '7', '15'],
       ['December', 'Week 3', '11', '15', '13', '8', '11', '11', '11'],
       ['December', 'Week 4', '7', '8', '6', '6', '15', '15', '15'],
       ['January', 'Week 1', '2', '8', '2', '6', '5', '2', '19'],
       ['January', 'Week 2', '4', '8', '4', '4', '3', '2', '22'],
       ['January', 'Week 3', '7', '7', '4', '6', '8', '7', '22'],
       ['J

In [30]:
cnd_nov=min_temp[:,0]=='November'
cnd_nov

array([False,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [31]:
nov2=min_temp[cnd_nov]
nov2

array([['November', '', 'Min Temp', 'Min Temp', 'Min Temp', 'Min Temp',
        'Min Temp', 'Min Temp', 'Min Temp'],
       ['November', 'Week 1', '6', '8', '14', '13', '12', '14', '6'],
       ['November', 'Week 2', '13', '14', '15', '-13', '14', '13', '11'],
       ['November', 'Week 3', '10', '7', '13', '10', '11', '10', '7'],
       ['November', 'Week 4', '7', '8', '8', '8', '8', '6', '8']],
      dtype='<U16')

In [32]:
#changing datatype to integer
t= nov2[1:,2:].astype(int)
t

array([[  6,   8,  14,  13,  12,  14,   6],
       [ 13,  14,  15, -13,  14,  13,  11],
       [ 10,   7,  13,  10,  11,  10,   7],
       [  7,   8,   8,   8,   8,   6,   8]])

In [33]:
week_1=t[0:1,:].reshape(7,)
week_1

array([ 6,  8, 14, 13, 12, 14,  6])

In [34]:
week_2=t[1:2,:].reshape(7,)
week_2

array([ 13,  14,  15, -13,  14,  13,  11])

In [35]:
week_3=t[2:3,:].reshape(7,)
week_3

array([10,  7, 13, 10, 11, 10,  7])

In [36]:
week_4=t[3:4,:].reshape(7,)
week_4

array([7, 8, 8, 8, 8, 6, 8])

In [37]:
# check where temp less than 8
w1=[]
for n in week_1:
    if n<8:
        w1.append(n)
    else:
        w1.append('')
print(w1)

[6, '', '', '', '', '', 6]


In [38]:
w2=[]
for n in week_2:
    if n<8:
        w2.append(n)
    else:
        w2.append('')
print(w2)

['', '', '', -13, '', '', '']


In [39]:
w3=[]
for n in week_3:
    if n<8:
        w3.append(n)
    else:
        w3.append('')
print(w3)

['', 7, '', '', '', '', 7]


In [40]:
w4=[]
for n in week_4:
    if n<8:
        w4.append(n)
    else:
        w4.append('')
print(w4)

[7, '', '', '', '', 6, '']


In [41]:
#conerting list t array
w1=np.array(w1).reshape(1,7)
w2=np.array(w2).reshape(1,7)
w3=np.array(w3).reshape(1,7)
w4=np.array(w4).reshape(1,7)

In [42]:
temp_nov=np.vstack(((w1,w2,w3,w4)))
temp_nov

array([['6', '', '', '', '', '', '6'],
       ['', '', '', '-13', '', '', ''],
       ['', '7', '', '', '', '', '7'],
       ['7', '', '', '', '', '6', '']], dtype='<U11')

In [43]:
less_temp=np.hstack((nov2[1:5,:2],temp_nov))
less_temp

array([['November', 'Week 1', '6', '', '', '', '', '', '6'],
       ['November', 'Week 2', '', '', '', '-13', '', '', ''],
       ['November', 'Week 3', '', '7', '', '', '', '', '7'],
       ['November', 'Week 4', '7', '', '', '', '', '6', '']], dtype='<U16')

**Q7 Print all the weeks in dec and jan where the max temp has crossed the threshold of 20 degrees.**

In [44]:
max_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['November', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['November', 'Week 1', '32', '29', '31', '27', '29', '23', '27'],
       ['November', 'Week 2', '21', '26', '32', '29', '29', '30', '30'],
       ['November', 'Week 3', '22', '20', '21', '30', '21', '28', '21'],
       ['November', 'Week 4', '20', '31', '32', '24', '32', '21', '30'],
       ['December', 'Week 1', '28', '26', '22', '27', '31', '23', '26'],
       ['December', 'Week 2', '32', '32', '21', '28', '23', '28', '21'],
       ['December', 'Week 3', '28', '27', '32', '22', '28', '23', '30'],
       ['December', 'Week 4', '27', '25', '21', '32', '20', '22', '23'],
       ['January', 'Week 1', '22', '21', '19', '21', '19', '7', '7'],
       ['January', 'Week 2', '18', '19', '21', '21', '22', '2', '6'],
       ['January', 'Week 3', '18', '18', '21', 

In [45]:
cond_dec=max_temp[:,0]=='December'

In [46]:
cond_jan=max_temp[:,0]=='January'

In [47]:
dec_jan=np.vstack((max_temp[cond_dec],max_temp[cond_jan]))
dec_jan

array([['December', 'Week 1', '28', '26', '22', '27', '31', '23', '26'],
       ['December', 'Week 2', '32', '32', '21', '28', '23', '28', '21'],
       ['December', 'Week 3', '28', '27', '32', '22', '28', '23', '30'],
       ['December', 'Week 4', '27', '25', '21', '32', '20', '22', '23'],
       ['January', 'Week 1', '22', '21', '19', '21', '19', '7', '7'],
       ['January', 'Week 2', '18', '19', '21', '21', '22', '2', '6'],
       ['January', 'Week 3', '18', '18', '21', '19', '22', '5', '5'],
       ['January', 'Week 4', '21', '19', '18', '18', '18', '6', '8']],
      dtype='<U16')

In [48]:
dw1=dec_jan[0,2:].reshape(7,).astype(int)
dw2=dec_jan[1,2:].reshape(7,).astype(int)
dw3=dec_jan[2,2:].reshape(7,).astype(int)
dw4=dec_jan[3,2:].reshape(7,).astype(int)

In [49]:
jw1=dec_jan[4,2:].reshape(7,).astype(int)
jw2=dec_jan[5,2:].reshape(7,).astype(int)
jw3=dec_jan[6,2:].reshape(7,).astype(int)
jw4=dec_jan[7,2:].reshape(7,).astype(int)

In [50]:
d_w1=[]
for i in dw1:
    if i>20:
        d_w1.append(i)
    else:
        d_w1.append('')
print(d_w1)

[28, 26, 22, 27, 31, 23, 26]


In [51]:
d_w2=[]
for i in dw2:
    if i>20:
        d_w2.append(i)
    else:
        d_w2.append('')
print(d_w2)

[32, 32, 21, 28, 23, 28, 21]


In [52]:
d_w3=[]
for i in dw3:
    if i>20:
        d_w3.append(i)
    else:
        d_w3.append('')
print(d_w3)

[28, 27, 32, 22, 28, 23, 30]


In [53]:
d_w4=[]
for i in dw4:
    if i>20:
        d_w4.append(i)
    else:
        d_w4.append('')
print(d_w4)

[27, 25, 21, 32, '', 22, 23]


In [57]:
j_w1=[]
for i in jw1:
    if i>20:
        j_w1.append(i)
    else:
        j_w1.append('')
print(j_w1)

j_w2=[]
for i in jw2:
    if i>20:
        j_w2.append(i)
    else:
        j_w2.append('')
print(j_w2)

j_w3=[]
for i in jw3:
    if i>20:
        j_w3.append(i)
    else:
        j_w3.append('')
print(j_w3)

j_w4=[]
for i in jw4:
    if i>20:
        j_w4.append(i)
    else:
        j_w4.append('')
print(j_w4)

[22, 21, '', 21, '', '', '']
['', '', 21, 21, 22, '', '']
['', '', 21, '', 22, '', '']
[21, '', '', '', '', '', '']


In [58]:
d_w1=np.array(d_w1).reshape(1,7)
d_w2=np.array(d_w2).reshape(1,7)
d_w3=np.array(d_w3).reshape(1,7)
d_w4=np.array(d_w4).reshape(1,7)

In [59]:
j_w1=np.array(j_w1).reshape(1,7)
j_w2=np.array(j_w2).reshape(1,7)
j_w3=np.array(j_w3).reshape(1,7)
j_w4=np.array(j_w4).reshape(1,7)

In [60]:
temp2=np.vstack((((((((d_w1,d_w2,d_w3,d_w4,j_w1,j_w2,j_w3,j_w4))))))))

In [61]:
temp2

array([['28', '26', '22', '27', '31', '23', '26'],
       ['32', '32', '21', '28', '23', '28', '21'],
       ['28', '27', '32', '22', '28', '23', '30'],
       ['27', '25', '21', '32', '', '22', '23'],
       ['22', '21', '', '21', '', '', ''],
       ['', '', '21', '21', '22', '', ''],
       ['', '', '21', '', '22', '', ''],
       ['21', '', '', '', '', '', '']], dtype='<U11')

In [62]:
temp_greater_20=np.hstack((dec_jan[:,:2],temp2))
temp_greater_20

array([['December', 'Week 1', '28', '26', '22', '27', '31', '23', '26'],
       ['December', 'Week 2', '32', '32', '21', '28', '23', '28', '21'],
       ['December', 'Week 3', '28', '27', '32', '22', '28', '23', '30'],
       ['December', 'Week 4', '27', '25', '21', '32', '', '22', '23'],
       ['January', 'Week 1', '22', '21', '', '21', '', '', ''],
       ['January', 'Week 2', '', '', '21', '21', '22', '', ''],
       ['January', 'Week 3', '', '', '21', '', '22', '', ''],
       ['January', 'Week 4', '21', '', '', '', '', '', '']], dtype='<U16')

**Q8 check if any adsurd alue present in the dataset.**

In [63]:
data[0:3]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '6', '32', '8', '29', '14', '31', '13',
        '27', '12', '29', '14', '23', '6', '27']], dtype='<U16')

In [64]:
D1=data[2:,2:]
D1

array([['6', '32', '8', '29', '14', '31', '13', '27', '12', '29', '14',
        '23', '6', '27'],
       ['13', '21', '14', '26', '15', '32', '-13', '29', '14', '29',
        '13', '30', '11', '30'],
       ['10', '22', '7', '20', '13', '21', '10', '30', '11', '21', '10',
        '28', '7', '21'],
       ['7', '20', '8', '31', '8', '32', '8', '24', '8', '32', '6', '21',
        '8', '30'],
       ['14', '28', '14', '26', '15', '22', '6', '27', '9', '31', '11',
        '23', '14', '26'],
       ['6', '32', '11', '32', '11', '21', '9', '28', '13', '23', '7',
        '28', '15', '21'],
       ['11', '28', '15', '27', '13', '32', '8', '22', '11', '28', '11',
        '23', '11', '30'],
       ['7', '27', '8', '25', '6', '21', '6', '32', '15', '20', '15',
        '22', '15', '23'],
       ['2', '22', '8', '21', '2', '19', '6', '21', '5', '19', '2', '7',
        '19', '7'],
       ['4', '18', '8', '19', '4', '21', '4', '21', '3', '22', '2', '2',
        '22', '6'],
       ['7', '18', '7', '18

In [65]:
cond = D1 ==''

In [66]:
D1[cond]

array([], dtype='<U16')

**Q9 What Strategy would you use to handle such data.**

*Mainly for the categorical data , where the valuse are missing.

**Q10 Find and print Indexes of all the outlier(unusual) values present in the above dataset**

In [67]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '6', '32', '8', '29', '14', '31', '13',
        '27', '12', '29', '14', '23', '6', '27'],
       ['November', 'Week 2', '13', '21', '14', '26', '15', '32', '-13',
        '29', '14', '29', '13', '30', '11', '30'],
       ['November', 'Week 3', '10', '22', '7', '20', '13', '21', '10',
        '30', '11', '21', '10', '28', '7', '21'],
       ['November', 'Week 4', '7', '20', '8', '31', '8', '32', '8', '24',
        '8', '32', '6', '21', '8', '30'],
       ['December', 'Week 1', '14', '28', '14', '26', '15', '22', '6',
        '27', '9', '31', '11', '23', '14'

In [69]:
temp_1=data[2:,2:].astype(int)
temp_1

array([[  6,  32,   8,  29,  14,  31,  13,  27,  12,  29,  14,  23,   6,
         27],
       [ 13,  21,  14,  26,  15,  32, -13,  29,  14,  29,  13,  30,  11,
         30],
       [ 10,  22,   7,  20,  13,  21,  10,  30,  11,  21,  10,  28,   7,
         21],
       [  7,  20,   8,  31,   8,  32,   8,  24,   8,  32,   6,  21,   8,
         30],
       [ 14,  28,  14,  26,  15,  22,   6,  27,   9,  31,  11,  23,  14,
         26],
       [  6,  32,  11,  32,  11,  21,   9,  28,  13,  23,   7,  28,  15,
         21],
       [ 11,  28,  15,  27,  13,  32,   8,  22,  11,  28,  11,  23,  11,
         30],
       [  7,  27,   8,  25,   6,  21,   6,  32,  15,  20,  15,  22,  15,
         23],
       [  2,  22,   8,  21,   2,  19,   6,  21,   5,  19,   2,   7,  19,
          7],
       [  4,  18,   8,  19,   4,  21,   4,  21,   3,  22,   2,   2,  22,
          6],
       [  7,  18,   7,  18,   4,  21,   6,  19,   8,  22,   7,   5,  22,
          5],
       [  4,  21,   8,  19,   8,  18,   2, 

In [70]:
temp_1.shape

(16, 14)

In [71]:
temp_1=temp_1.reshape(16*14,)
temp_1

array([  6,  32,   8,  29,  14,  31,  13,  27,  12,  29,  14,  23,   6,
        27,  13,  21,  14,  26,  15,  32, -13,  29,  14,  29,  13,  30,
        11,  30,  10,  22,   7,  20,  13,  21,  10,  30,  11,  21,  10,
        28,   7,  21,   7,  20,   8,  31,   8,  32,   8,  24,   8,  32,
         6,  21,   8,  30,  14,  28,  14,  26,  15,  22,   6,  27,   9,
        31,  11,  23,  14,  26,   6,  32,  11,  32,  11,  21,   9,  28,
        13,  23,   7,  28,  15,  21,  11,  28,  15,  27,  13,  32,   8,
        22,  11,  28,  11,  23,  11,  30,   7,  27,   8,  25,   6,  21,
         6,  32,  15,  20,  15,  22,  15,  23,   2,  22,   8,  21,   2,
        19,   6,  21,   5,  19,   2,   7,  19,   7,   4,  18,   8,  19,
         4,  21,   4,  21,   3,  22,   2,   2,  22,   6,   7,  18,   7,
        18,   4,  21,   6,  19,   8,  22,   7,   5,  22,   5,   4,  21,
         8,  19,   8,  18,   2,  18,   7,  18,   3,   6,  18,   8,  11,
        21,  11,  21, -10,  20,   7,  22,  12,  19,  11,  71,  2

In [72]:
sort_temp_1=np.sort(temp_1)
sort_temp_1

array([-13, -10,   2,   2,   2,   2,   2,   2,   3,   3,   4,   4,   4,
         4,   4,   5,   5,   5,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   9,   9,   9,
         9,   9,  10,  10,  10,  10,  10,  10,  11,  11,  11,  11,  11,
        11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  12,
        12,  12,  12,  12,  12,  12,  12,  12,  13,  13,  13,  13,  13,
        13,  14,  14,  14,  14,  14,  14,  14,  15,  15,  15,  15,  15,
        15,  15,  18,  18,  18,  18,  18,  18,  18,  18,  18,  19,  19,
        19,  19,  19,  19,  19,  19,  19,  19,  19,  20,  20,  20,  20,
        20,  20,  20,  20,  20,  21,  21,  21,  21,  21,  21,  21,  21,
        21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  2

In [73]:
mean=round(np.mean(temp_1),3)
mean

15.786

In [74]:
std=np.std(temp_1)
std

9.345480736916727

In [76]:
q1=np.median(sort_temp_1[0:112])
q3=np.median(sort_temp_1[112:])
print(q1,q3)

8.0 22.0


In [77]:
iqr=q3-q1
iqr

14.0

In [80]:
Z=[]
for i in temp_1:
    if i>q1-1.5*iqr and i<q3+15*iqr:
        Z.append(i)
    else:
        Z.append('outlier')
print(Z)

[6, 32, 8, 29, 14, 31, 13, 27, 12, 29, 14, 23, 6, 27, 13, 21, 14, 26, 15, 32, 'outlier', 29, 14, 29, 13, 30, 11, 30, 10, 22, 7, 20, 13, 21, 10, 30, 11, 21, 10, 28, 7, 21, 7, 20, 8, 31, 8, 32, 8, 24, 8, 32, 6, 21, 8, 30, 14, 28, 14, 26, 15, 22, 6, 27, 9, 31, 11, 23, 14, 26, 6, 32, 11, 32, 11, 21, 9, 28, 13, 23, 7, 28, 15, 21, 11, 28, 15, 27, 13, 32, 8, 22, 11, 28, 11, 23, 11, 30, 7, 27, 8, 25, 6, 21, 6, 32, 15, 20, 15, 22, 15, 23, 2, 22, 8, 21, 2, 19, 6, 21, 5, 19, 2, 7, 19, 7, 4, 18, 8, 19, 4, 21, 4, 21, 3, 22, 2, 2, 22, 6, 7, 18, 7, 18, 4, 21, 6, 19, 8, 22, 7, 5, 22, 5, 4, 21, 8, 19, 8, 18, 2, 18, 7, 18, 3, 6, 18, 8, 11, 21, 11, 21, -10, 20, 7, 22, 12, 19, 11, 71, 20, 12, 12, 22, 9, 20, 8, 20, 7, 20, 8, 19, 11, 7, 22, 7, 10, 18, 8, 18, 11, 21, 11, 22, 12, 21, 11, 9, 19, 10, 11, 22, 12, 21, 12, 19, 7, 19, 10, 20, 12, 9, 22, 12]


In [81]:
reshape=np.array(Z).reshape(16,14)
reshape

array([['6', '32', '8', '29', '14', '31', '13', '27', '12', '29', '14',
        '23', '6', '27'],
       ['13', '21', '14', '26', '15', '32', 'outlier', '29', '14', '29',
        '13', '30', '11', '30'],
       ['10', '22', '7', '20', '13', '21', '10', '30', '11', '21', '10',
        '28', '7', '21'],
       ['7', '20', '8', '31', '8', '32', '8', '24', '8', '32', '6', '21',
        '8', '30'],
       ['14', '28', '14', '26', '15', '22', '6', '27', '9', '31', '11',
        '23', '14', '26'],
       ['6', '32', '11', '32', '11', '21', '9', '28', '13', '23', '7',
        '28', '15', '21'],
       ['11', '28', '15', '27', '13', '32', '8', '22', '11', '28', '11',
        '23', '11', '30'],
       ['7', '27', '8', '25', '6', '21', '6', '32', '15', '20', '15',
        '22', '15', '23'],
       ['2', '22', '8', '21', '2', '19', '6', '21', '5', '19', '2', '7',
        '19', '7'],
       ['4', '18', '8', '19', '4', '21', '4', '21', '3', '22', '2', '2',
        '22', '6'],
       ['7', '18', '7',

**Q11 Replace the outliers with appropriate value**

In [83]:
S=[]
for i in Z:
    if i!='outlier':
        S.append(i)
    else:
        S.append(mean)
print(S)
        

[6, 32, 8, 29, 14, 31, 13, 27, 12, 29, 14, 23, 6, 27, 13, 21, 14, 26, 15, 32, 15.786, 29, 14, 29, 13, 30, 11, 30, 10, 22, 7, 20, 13, 21, 10, 30, 11, 21, 10, 28, 7, 21, 7, 20, 8, 31, 8, 32, 8, 24, 8, 32, 6, 21, 8, 30, 14, 28, 14, 26, 15, 22, 6, 27, 9, 31, 11, 23, 14, 26, 6, 32, 11, 32, 11, 21, 9, 28, 13, 23, 7, 28, 15, 21, 11, 28, 15, 27, 13, 32, 8, 22, 11, 28, 11, 23, 11, 30, 7, 27, 8, 25, 6, 21, 6, 32, 15, 20, 15, 22, 15, 23, 2, 22, 8, 21, 2, 19, 6, 21, 5, 19, 2, 7, 19, 7, 4, 18, 8, 19, 4, 21, 4, 21, 3, 22, 2, 2, 22, 6, 7, 18, 7, 18, 4, 21, 6, 19, 8, 22, 7, 5, 22, 5, 4, 21, 8, 19, 8, 18, 2, 18, 7, 18, 3, 6, 18, 8, 11, 21, 11, 21, -10, 20, 7, 22, 12, 19, 11, 71, 20, 12, 12, 22, 9, 20, 8, 20, 7, 20, 8, 19, 11, 7, 22, 7, 10, 18, 8, 18, 11, 21, 11, 22, 12, 21, 11, 9, 19, 10, 11, 22, 12, 21, 12, 19, 7, 19, 10, 20, 12, 9, 22, 12]


In [84]:
reshape_2=np.array(S).reshape(16,14)
reshape_2

array([[  6.   ,  32.   ,   8.   ,  29.   ,  14.   ,  31.   ,  13.   ,
         27.   ,  12.   ,  29.   ,  14.   ,  23.   ,   6.   ,  27.   ],
       [ 13.   ,  21.   ,  14.   ,  26.   ,  15.   ,  32.   ,  15.786,
         29.   ,  14.   ,  29.   ,  13.   ,  30.   ,  11.   ,  30.   ],
       [ 10.   ,  22.   ,   7.   ,  20.   ,  13.   ,  21.   ,  10.   ,
         30.   ,  11.   ,  21.   ,  10.   ,  28.   ,   7.   ,  21.   ],
       [  7.   ,  20.   ,   8.   ,  31.   ,   8.   ,  32.   ,   8.   ,
         24.   ,   8.   ,  32.   ,   6.   ,  21.   ,   8.   ,  30.   ],
       [ 14.   ,  28.   ,  14.   ,  26.   ,  15.   ,  22.   ,   6.   ,
         27.   ,   9.   ,  31.   ,  11.   ,  23.   ,  14.   ,  26.   ],
       [  6.   ,  32.   ,  11.   ,  32.   ,  11.   ,  21.   ,   9.   ,
         28.   ,  13.   ,  23.   ,   7.   ,  28.   ,  15.   ,  21.   ],
       [ 11.   ,  28.   ,  15.   ,  27.   ,  13.   ,  32.   ,   8.   ,
         22.   ,  11.   ,  28.   ,  11.   ,  23.   ,  11.   ,  30.   ],

**Q12 Find the average max temp for the winter month in Jaipur.**

In [85]:
temp=max_temp[2:,2:].astype(int)
temp

array([[32, 29, 31, 27, 29, 23, 27],
       [21, 26, 32, 29, 29, 30, 30],
       [22, 20, 21, 30, 21, 28, 21],
       [20, 31, 32, 24, 32, 21, 30],
       [28, 26, 22, 27, 31, 23, 26],
       [32, 32, 21, 28, 23, 28, 21],
       [28, 27, 32, 22, 28, 23, 30],
       [27, 25, 21, 32, 20, 22, 23],
       [22, 21, 19, 21, 19,  7,  7],
       [18, 19, 21, 21, 22,  2,  6],
       [18, 18, 21, 19, 22,  5,  5],
       [21, 19, 18, 18, 18,  6,  8],
       [21, 21, 20, 22, 19, 71, 12],
       [22, 20, 20, 20, 19,  7,  7],
       [18, 18, 21, 22, 21,  9, 10],
       [22, 21, 19, 19, 20,  9, 12]])

In [86]:
np.max(temp)

71

In [87]:
np.mean(temp)

21.955357142857142

In [88]:
np.median(temp)

21.0

**Q13 Find the weekly min average temp for the month of dec in jaipur.**

In [89]:
min_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['November', '', 'Min Temp', 'Min Temp', 'Min Temp', 'Min Temp',
        'Min Temp', 'Min Temp', 'Min Temp'],
       ['November', 'Week 1', '6', '8', '14', '13', '12', '14', '6'],
       ['November', 'Week 2', '13', '14', '15', '-13', '14', '13', '11'],
       ['November', 'Week 3', '10', '7', '13', '10', '11', '10', '7'],
       ['November', 'Week 4', '7', '8', '8', '8', '8', '6', '8'],
       ['December', 'Week 1', '14', '14', '15', '6', '9', '11', '14'],
       ['December', 'Week 2', '6', '11', '11', '9', '13', '7', '15'],
       ['December', 'Week 3', '11', '15', '13', '8', '11', '11', '11'],
       ['December', 'Week 4', '7', '8', '6', '6', '15', '15', '15'],
       ['January', 'Week 1', '2', '8', '2', '6', '5', '2', '19'],
       ['January', 'Week 2', '4', '8', '4', '4', '3', '2', '22'],
       ['January', 'Week 3', '7', '7', '4', '6', '8', '7', '22'],
       ['J

In [91]:
dec_min_w1=min_temp[6:7,2:].astype(int)
dec_min_w2=min_temp[7:8,2:].astype(int)
dec_min_w3=min_temp[8:9,2:].astype(int)
dec_min_w4=min_temp[9:10,2:].astype(int)

In [92]:
print("Min. avg.temp. of week 1 :- ",np.mean(dec_min_w1))
print("Min. avg.temp. of week 2 :- ",np.mean(dec_min_w2))
print("Min. avg.temp. of week 3 :- ",np.mean(dec_min_w3))
print("Min. avg.temp. of week 4 :- ",np.mean(dec_min_w4))

Min. avg.temp. of week 1 :-  11.857142857142858
Min. avg.temp. of week 2 :-  10.285714285714286
Min. avg.temp. of week 3 :-  11.428571428571429
Min. avg.temp. of week 4 :-  10.285714285714286


**Q14 Find the overall average temp for the month of Dec and Jan.**

In [93]:
data[0:3]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '6', '32', '8', '29', '14', '31', '13',
        '27', '12', '29', '14', '23', '6', '27']], dtype='<U16')

In [94]:
cond_dec=data[0:,0]=='December'
dec_temp=data[cond_dec]
dec_temp=dec_temp[:,2:].astype(int)
dec_temp

array([[14, 28, 14, 26, 15, 22,  6, 27,  9, 31, 11, 23, 14, 26],
       [ 6, 32, 11, 32, 11, 21,  9, 28, 13, 23,  7, 28, 15, 21],
       [11, 28, 15, 27, 13, 32,  8, 22, 11, 28, 11, 23, 11, 30],
       [ 7, 27,  8, 25,  6, 21,  6, 32, 15, 20, 15, 22, 15, 23]])

In [95]:
cond_jan=data[0:,0]=='January'
jan_temp=data[cond_jan]
jan_temp=jan_temp[:,2:].astype(int)
jan_temp

array([[ 2, 22,  8, 21,  2, 19,  6, 21,  5, 19,  2,  7, 19,  7],
       [ 4, 18,  8, 19,  4, 21,  4, 21,  3, 22,  2,  2, 22,  6],
       [ 7, 18,  7, 18,  4, 21,  6, 19,  8, 22,  7,  5, 22,  5],
       [ 4, 21,  8, 19,  8, 18,  2, 18,  7, 18,  3,  6, 18,  8]])

In [96]:
M1=np.mean(dec_temp)

18.482142857142858

In [97]:
M2=np.mean(jan_temp)

11.482142857142858

In [100]:
np.mean(np.vstack((dec_temp,jan_temp)))

14.982142857142858

**Q15 Find the least temperature experienced by the city in the month of December and January . Also Print the exact date of the same.**

In [129]:
dec_jan_temp=np.vstack((dec_temp,jan_temp))
dec_jan_temp

array([[14, 28, 14, 26, 15, 22,  6, 27,  9, 31, 11, 23, 14, 26],
       [ 6, 32, 11, 32, 11, 21,  9, 28, 13, 23,  7, 28, 15, 21],
       [11, 28, 15, 27, 13, 32,  8, 22, 11, 28, 11, 23, 11, 30],
       [ 7, 27,  8, 25,  6, 21,  6, 32, 15, 20, 15, 22, 15, 23],
       [ 2, 22,  8, 21,  2, 19,  6, 21,  5, 19,  2,  7, 19,  7],
       [ 4, 18,  8, 19,  4, 21,  4, 21,  3, 22,  2,  2, 22,  6],
       [ 7, 18,  7, 18,  4, 21,  6, 19,  8, 22,  7,  5, 22,  5],
       [ 4, 21,  8, 19,  8, 18,  2, 18,  7, 18,  3,  6, 18,  8]])

In [130]:
least_temp=np.min(dec_jan_temp)
least_temp

2

In [131]:
d_j=np.hstack((data[6:14,0:2],dec_jan_temp[:,:]))

In [132]:
d_j=np.vstack((data[0:2,:],d_j))

In [133]:
d_j

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['December', 'Week 1', '14', '28', '14', '26', '15', '22', '6',
        '27', '9', '31', '11', '23', '14', '26'],
       ['December', 'Week 2', '6', '32', '11', '32', '11', '21', '9',
        '28', '13', '23', '7', '28', '15', '21'],
       ['December', 'Week 3', '11', '28', '15', '27', '13', '32', '8',
        '22', '11', '28', '11', '23', '11', '30'],
       ['December', 'Week 4', '7', '27', '8', '25', '6', '21', '6', '32',
        '15', '20', '15', '22', '15', '23'],
       ['January', 'Week 1', '2', '22', '8', '21', '2', '19', '6', '21',
        '5', '19', '2', '7', '19', '7'

In [134]:
cod=d_j[:,2]=='2'
cod

array([False, False, False, False, False, False,  True, False, False,
       False])

In [135]:
cod=d_j[:,3]=='2'
cod

array([False, False, False, False, False, False, False, False, False,
       False])

In [136]:
cod=d_j[:,4]=='2'
cod

array([False, False, False, False, False, False, False, False, False,
       False])

In [137]:
d_j[cod]

array([], shape=(0, 16), dtype='<U16')